### ISSUE TITLE
Version for stable is very behind

### ISSUE THREAD

**Issue by shlozm** [ivan-hc/MS-Edge-appimage#2]
Hi, just wanted to let you know that the version for microsoft-edge-stable that builds out is very behind the current stable release. Currently if downloading the deb from Microsoft's website or installing it through apt the stable version is 120.x not 112.x
(It would seem the source mechanism in the script is sourcing the wrong version, sorry I don't understand coding well enough to see what's wrong...)

Thanks for this great asset! Much appreciated

**Comment by shlozm** [comment]
The proper deb is located at: https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/
I don't know how one can script to get the latest version though...

**Comment by ivan-hc** [comment]
https://repology.org is a great source for this, I've experimented this in other installation scripts just 2 days ago ;)

Newser version will poin on this:
```
wget -q https://repology.org/project/microsoft-edge/versions -O - | grep "newest version" | head -1 | grep -o -P '(?<=">).*(?=</a)' | sed 's/^.*>//'
```
I'm starting the workflow right now

**Comment by shlozm** [comment]
Thank you!!!

**Comment by ivan-hc** [comment]
Thanks to you, if everyone would just report bugs instead of lamenting around on the forums, not just my works but all the software would be better!

PS: just seen that on repology the beta and dev versions have various numbers https://repology.org/project/microsoft-edge/versions , I hope this would not be a problem
