### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by erickwill** [ivan-hc/MS-Edge-appimage#4]
First off, thanks for make this possible for Linux! I wonder if could you make also available, beyond the .AppImage package, an also portable zipped folder for Edge (same as Thorium has made available https://github.com/Alex313031/thorium/releases/download/M120.0.6099.235/thorium-browser_120.0.6099.235_amd64.zip). It would be awesome to have both options to go with.
Thanks in advance and keep it up

**Comment by ivan-hc** [comment]
Hi @erickwill , the point is that MS Edge is extracted from the official .deb package. All I can do is to convert it into an AppImage... which I don't think is very legitimate, since it's proprietary software... it's already risky for me and they might contact me telling me to stop.

In any case, the distribution of applications in a different format, be it zip/tar/exe... It is solely at the discretion of the developers.

Appimages are something else. Building an Appimage has its advantages, as it is a separate file system... Have you ever tried to run the command `./*. AppImage --appimage-help`? These are not things you could do with a zip archive.

Moreover, if it is officially distributed as a .deb package it is to integrate into the system, into the filesystem of the host. The AppImage acts as an "isolator", so to speak... it's not isolated by default, but being a portable package you can isolate it with Firejail and more.
